name: MCPhotography
favicon: null
layout_spectrum: 0.01522933878004551
typography_spectrum: 0.9688923640642315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.662714232923463
  lightness: 0.020398504566401243
  saturation: 0.996395499445498
  rhythmicContrast: 0.1744216037914157
purpose: []
